//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид поддержки.
    /// </summary>
    // *** Start programmer edit section *** (ВидПоддержки CustomAttributes)

    // *** End programmer edit section *** (ВидПоддержки CustomAttributes)
    [AutoAltered()]
    [Caption("Вид поддержки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидПоддержкиE", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Пользователь.ФИО"})]
    [MasterViewDefineAttribute("ВидПоддержкиE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ВидПоддержкиL", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "Пользователь.ФИО as \'ФИО\'"})]
    public class ВидПоддержки : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fОписание;
        
        private IIS.ISS8.Пользователь fПользователь;
        
        // *** Start programmer edit section *** (ВидПоддержки CustomMembers)

        // *** End programmer edit section *** (ВидПоддержки CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Описание CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Описание Get start)

                // *** End programmer edit section *** (ВидПоддержки.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (ВидПоддержки.Описание Get end)

                // *** End programmer edit section *** (ВидПоддержки.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Описание Set start)

                // *** End programmer edit section *** (ВидПоддержки.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (ВидПоддержки.Описание Set end)

                // *** End programmer edit section *** (ВидПоддержки.Описание Set end)
            }
        }
        
        /// <summary>
        /// Вид поддержки.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Пользователь CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Пользователь CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS8.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Get start)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Get start)
                IIS.ISS8.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Get end)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Set start)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Set end)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидПоддержкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидПоддержкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидПоддержкиE", typeof(IIS.ISS8.ВидПоддержки));
                }
            }
            
            /// <summary>
            /// "ВидПоддержкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидПоддержкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидПоддержкиL", typeof(IIS.ISS8.ВидПоддержки));
                }
            }
        }
    }
}
