//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Условие.
    /// </summary>
    // *** Start programmer edit section *** (Условие CustomAttributes)

    // *** End programmer edit section *** (Условие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УсловиеE", new string[] {
            "НомерФормы as \'Номер формы\'",
            "Наименование as \'Наименование\'",
            "ВидПоддержки as \'Вид поддержки\'",
            "ВидПоддержки.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ВидПоддержки.Наименование"})]
    [MasterViewDefineAttribute("УсловиеE", "ВидПоддержки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Условие : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерФормы;
        
        private string fНаименование;
        
        private IIS.ISS8.ВидПоддержки fВидПоддержки;
        
        private IIS.ISS8.Форма fФорма;
        
        // *** Start programmer edit section *** (Условие CustomMembers)

        // *** End programmer edit section *** (Условие CustomMembers)

        
        /// <summary>
        /// НомерФормы.
        /// </summary>
        // *** Start programmer edit section *** (Условие.НомерФормы CustomAttributes)

        // *** End programmer edit section *** (Условие.НомерФормы CustomAttributes)
        [StrLen(255)]
        public virtual string НомерФормы
        {
            get
            {
                // *** Start programmer edit section *** (Условие.НомерФормы Get start)

                // *** End programmer edit section *** (Условие.НомерФормы Get start)
                string result = this.fНомерФормы;
                // *** Start programmer edit section *** (Условие.НомерФормы Get end)

                // *** End programmer edit section *** (Условие.НомерФормы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.НомерФормы Set start)

                // *** End programmer edit section *** (Условие.НомерФормы Set start)
                this.fНомерФормы = value;
                // *** Start programmer edit section *** (Условие.НомерФормы Set end)

                // *** End programmer edit section *** (Условие.НомерФормы Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Условие.Наименование CustomAttributes)

        // *** End programmer edit section *** (Условие.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Условие.Наименование Get start)

                // *** End programmer edit section *** (Условие.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Условие.Наименование Get end)

                // *** End programmer edit section *** (Условие.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.Наименование Set start)

                // *** End programmer edit section *** (Условие.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Условие.Наименование Set end)

                // *** End programmer edit section *** (Условие.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Условие.
        /// </summary>
        // *** Start programmer edit section *** (Условие.ВидПоддержки CustomAttributes)

        // *** End programmer edit section *** (Условие.ВидПоддержки CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS8.ВидПоддержки ВидПоддержки
        {
            get
            {
                // *** Start programmer edit section *** (Условие.ВидПоддержки Get start)

                // *** End programmer edit section *** (Условие.ВидПоддержки Get start)
                IIS.ISS8.ВидПоддержки result = this.fВидПоддержки;
                // *** Start programmer edit section *** (Условие.ВидПоддержки Get end)

                // *** End programmer edit section *** (Условие.ВидПоддержки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.ВидПоддержки Set start)

                // *** End programmer edit section *** (Условие.ВидПоддержки Set start)
                this.fВидПоддержки = value;
                // *** Start programmer edit section *** (Условие.ВидПоддержки Set end)

                // *** End programmer edit section *** (Условие.ВидПоддержки Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ISS8.Форма.
        /// </summary>
        // *** Start programmer edit section *** (Условие.Форма CustomAttributes)

        // *** End programmer edit section *** (Условие.Форма CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.ISS8.Форма Форма
        {
            get
            {
                // *** Start programmer edit section *** (Условие.Форма Get start)

                // *** End programmer edit section *** (Условие.Форма Get start)
                IIS.ISS8.Форма result = this.fФорма;
                // *** Start programmer edit section *** (Условие.Форма Get end)

                // *** End programmer edit section *** (Условие.Форма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.Форма Set start)

                // *** End programmer edit section *** (Условие.Форма Set start)
                this.fФорма = value;
                // *** Start programmer edit section *** (Условие.Форма Set end)

                // *** End programmer edit section *** (Условие.Форма Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УсловиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеE", typeof(IIS.ISS8.Условие));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Условие.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУсловие CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУсловие CustomAttributes)
    public class DetailArrayOfУсловие : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ISS8.DetailArrayOfУсловие members)

        // *** End programmer edit section *** (IIS.ISS8.DetailArrayOfУсловие members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Условие by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Условие.
        /// </summary>
        public DetailArrayOfУсловие(IIS.ISS8.Форма fФорма) : 
                base(typeof(Условие), ((ICSSoft.STORMNET.DataObject)(fФорма)))
        {
        }
        
        public IIS.ISS8.Условие this[int index]
        {
            get
            {
                return ((IIS.ISS8.Условие)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ISS8.Условие dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
